### ISSUE TITLE
Add method to quit quiz script

### ISSUE THREAD

**Issue by kljensen** [yale-cpsc-213-spring-2018/about-this-class#2]
Right now, it reads until a user issues control C or similar, is that right?

**Comment by jacobbendicksen** [comment]
Yeah. Should I add a note to that effect, or look for "done" or another quit command?

**Comment by kljensen** [comment]
I think a"done" or quit is perfect! Can post in Piazza that you updated
repo when done?

**Comment by jacobbendicksen** [comment]
Added in [3b1cf70](https://github.com/yale-cpsc-213-spring-2018/about-this-class/commit/3b1cf7048b7145d16033d201c2852507e43459eb)
