### ISSUE TITLE
Add feedback to quiz script

### ISSUE THREAD

**Issue by kljensen** [yale-cpsc-213-spring-2018/about-this-class#3]
It should show what quiz_submissions and quiz_answers were written

**Comment by jacobbendicksen** [comment]
As in, when a CURL request is sent it prints out what was sent?

**Comment by jacobbendicksen** [comment]
If so, fixed in [092690a](https://github.com/yale-cpsc-213-spring-2018/about-this-class/commit/092690a706121b44f23deeadd8e31818d1d03792)
